# Generated by Django 4.0.3 on 2022-04-14 00:02

import Api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido1', models.CharField(max_length=20, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(max_length=20, verbose_name='Segundo Apellido')),
                ('ci', models.FloatField(verbose_name='Número de carnet')),
                ('empresa', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('abonado', models.BooleanField(default=False)),
                ('telefono', models.FloatField()),
                ('email', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('nit', models.BigIntegerField(verbose_name='NIT')),
                ('Cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(verbose_name='Número del contrato')),
                ('anno', models.SmallIntegerField(verbose_name='Año')),
                ('otraPate', models.CharField(max_length=100, verbose_name='Otra parte')),
                ('codigoReeup', models.SmallIntegerField(verbose_name='Código REEUP')),
                ('cuentaBancaria', models.BigIntegerField(verbose_name='Cuenta bancaria en CUP')),
                ('representante', models.CharField(max_length=50, verbose_name='Representante')),
                ('caracter', models.CharField(max_length=20, verbose_name='Caracter')),
                ('resolucion', models.SmallIntegerField()),
                ('fechaResolucion', models.DateField()),
                ('emitidaPor', models.CharField(max_length=100, verbose_name='Emitida por')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
                ('nombre', models.CharField(max_length=30)),
                ('profesor', models.CharField(max_length=20)),
                ('duracionDias', models.SmallIntegerField(verbose_name='Días de duración')),
                ('horasTotales', models.SmallIntegerField(verbose_name='Horas de duración')),
                ('descripción', models.CharField(max_length=500)),
                ('enlaceMoodle', models.URLField(max_length=300)),
                ('costo', models.SmallIntegerField(verbose_name='Costo')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('abonado', models.BooleanField(default=False)),
                ('telefono', models.FloatField()),
                ('email', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('nit', models.BigIntegerField(verbose_name='NIT')),
                ('establecimientoDireccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('establecimiento', models.CharField(max_length=50)),
                ('nombreEspecialista', models.CharField(max_length=80, verbose_name='Especialista de calidad')),
                ('directorEntidad', models.CharField(max_length=80, verbose_name='Director de la entidad')),
                ('directorEstablecimiento', models.CharField(max_length=80, verbose_name='Director del establecimiento')),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado del contrato',
                'verbose_name_plural': 'Estados de contratos',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de solicitud',
                'verbose_name_plural': 'Estados de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(max_length=20, verbose_name='Segundo apellido')),
            ],
            options={
                'verbose_name': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='GestCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Gestión de certificado',
                'verbose_name_plural': 'Gestión de certificados',
            },
        ),
        migrations.CreateModel(
            name='Isos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Isos',
            },
        ),
        migrations.CreateModel(
            name='Magnitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitud', models.CharField(max_length=50, verbose_name='Magnitud')),
            ],
            options={
                'verbose_name_plural': 'Magnitudes',
            },
        ),
        migrations.CreateModel(
            name='NormaResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Resolución de la norma',
                'verbose_name_plural': 'Resoluciones de normas',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector económico',
                'verbose_name_plural': 'Sectores económicos',
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contratos',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de curso',
                'verbose_name_plural': 'Tipos de cursos',
            },
        ),
        migrations.CreateModel(
            name='TipoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de diagnóstico',
                'verbose_name_plural': 'Tipo de diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de entidad',
                'verbose_name_plural': 'Tipos de entidades',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de especialista',
                'verbose_name_plural': 'Tipos de especialistas',
            },
        ),
        migrations.CreateModel(
            name='TipoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de inspección',
                'verbose_name_plural': 'Tipos de inspecciones',
            },
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de instrumento',
                'verbose_name_plural': 'Tipos de instrumentos',
            },
        ),
        migrations.CreateModel(
            name='TipoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('codigo', models.SmallIntegerField(verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Tipo de norma',
                'verbose_name_plural': 'Tipos de normas',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de solicitud',
                'verbose_name_plural': 'Tipos de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='NotasCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.SmallIntegerField(verbose_name='Nota')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.cliente')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='NormaCuba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaExcepcion', models.DateField()),
                ('nombre', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('anno', models.SmallIntegerField(verbose_name='año')),
                ('pagina', models.SmallIntegerField(verbose_name='Página')),
                ('fechaValidacion', models.DateField(verbose_name='Fecha de validación')),
                ('fechaRegistro', models.DateField(verbose_name='Fecha de registro')),
                ('fechaAprovacion', models.DateField(verbose_name='Fecha de aprovación')),
                ('formatoDisponible', models.SmallIntegerField(verbose_name='Formato')),
                ('precio', models.SmallIntegerField()),
                ('observacion', models.CharField(max_length=80, verbose_name='Observación')),
                ('iso', models.ManyToManyField(to='Api.isos')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.normaresolucion')),
                ('tipoNorma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.tiponorma')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas de Cuba',
            },
        ),
        migrations.CreateModel(
            name='LevNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoServicio', models.BooleanField()),
                ('nombreNorma', models.CharField(max_length=40, verbose_name='Nombre de la norma')),
                ('numNorma', models.FloatField()),
                ('annoNorma', models.BigIntegerField(verbose_name='Año')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.tiponorma')),
            ],
            options={
                'verbose_name': 'Levantamiento de norma',
                'verbose_name_plural': 'Levantamientos de normas',
            },
        ),
        migrations.CreateModel(
            name='InspeccionSupervicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('objetoInspeccion', models.CharField(max_length=80, verbose_name='Objeto de inspección')),
                ('destinoProduccion', models.CharField(max_length=80, verbose_name='Destino de la producción')),
                ('fechaInspeccion', models.DateField(verbose_name='Fecha de la inspección')),
                ('fechaEmisionInf', models.DateField(verbose_name='Fecha de emisión del informe')),
                ('noConfDetectadas', models.CharField(max_length=2000, verbose_name='No conformidades detectadas')),
                ('Conforme', models.CharField(max_length=2000)),
                ('nombreInspector', models.CharField(max_length=50, verbose_name='Inspector')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.entidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.tipoentidad')),
            ],
            options={
                'verbose_name': 'Inspección / supervisión',
                'verbose_name_plural': 'Inspecciones y superviciones',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='gestionCertificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.gestcertificado'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='organismo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.organismo'),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivoAdjunto', models.FileField(null=True, upload_to=Api.models.documentoDiagnostico)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.cliente')),
                ('TipoDiagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.tipodiagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnóstico',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='Cliente',
            field=models.ManyToManyField(through='Api.NotasCurso', to='Api.cliente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Tematica',
            field=models.ManyToManyField(to='Api.tematica'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.tipocurso'),
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=20, verbose_name='Capítulo')),
                ('articulo', models.CharField(max_length=20, verbose_name='Artículo')),
                ('hallazgo', models.CharField(max_length=2000)),
                ('cumplio', models.BooleanField(default=False)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.entidad')),
            ],
            options={
                'verbose_name': 'Control de calidad',
                'verbose_name_plural': 'Controles de calidad',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='Organismo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.organismo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Sector_Economico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.sectoreconomico'),
        ),
    ]
